name: ndex-frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.5.2

    - name: Yarn Setup
      uses: DerYeger/yarn-setup-action@v1.0.1
      
    - name: Install dependencies
      run: yarn

    - name: Run Prettier
      run: yarn run prettier
    
    - name: Run ESLint 
      run: yarn run lint
    
